[project]
name = "questlog"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13.5"

authors = [
  { name = "Yehor Ternovyi", email = "yegorjke@gmail.com" }
]

dependencies = [
    "alembic>=1.16.4",
    "asyncpg>=0.30.0",
    "fastapi>=0.116.1",
    "psycopg2>=2.9.10",
    "pydantic-settings>=2.10.1",
    "sqlalchemy>=2.0.42",
    "uvicorn>=0.35.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.4.1",
    "ruff>=0.12.7",
]
